/*************************************************************************
 * Version      Date         Name                   Description
 * ***********************************************************************
 *   V1.0    18/03/2021    Developer 1        Add Method implemented
 * Date : 
 * 
 *************************************************************************/

 public with sharing class Calculator {
    public Calculator() {

    }
    public integer add(integer a, integer b)
     {
        return a+b;
    }

}
